== introducao-a-computacao-livro

Livro de Introdução a Computação - Computação - EAD - UFPB

== Linguagem de escrita

O livro está sendo escrito utilizando a linguagem asciidoc:

http://powerman.name/doc/asciidoc

=== Ferramentas

No windows usar o github for windows: http://github-windows.s3.amazonaws.com/GitHubSetup.exe

Editor de texto: http://www.sublimetext.com/

Plugin-in-assciidoc: https://github.com/SublimeText/AsciiDoc (ver instruções de instalação)

aap maker: http://www.a-a-p.org/

==== Gerando versão pdf

 aap pdf

WARNING: Certifique-se de que existe o diretório: '../pdf'

=== TODO e FIXME

Sempre que houver algo pendente, você pode adiconar um comentário TODO no texto,
por exemplo:

 // TODO Fazer uma ponte para o próximo capítulo.

O FIXME é utilizado para algo que está errado e precisa ser corrigido, 
geralmente resultado de uma revisão:

 // FIXME Este parágrafo não expressa idéias com clareza.

Em seguida, podemos utilizar o comando 'grep' para encontrar estas anotações:

 grep -n -E "TODO|FIXME" -r capitulos/ --color
 
 === Alteração fora da versão
 
 Esta alteração não faz parte da versão v1.0.0


